name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dos2unix zip

    - name: Generate Resume
      run: |
        dos2unix ./template.tex ./companies.tex
        ./gen-resumes.sh ./template.tex ./companies.tex

    - name: Zip Generated Files
      run: |
        zip -r resume_files.zip ./output/

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ github.run_number }}
        release_name: "Release ${{ github.run_number }}"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Resume Zip to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./resume_files.zip
        asset_name: resume_files.zip
        asset_content_type: application/zip
